# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-01-27T19:15:58+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Field


class Error(BaseModel):
    error: str = Field(..., description='Error message')
    code: int = Field(..., description='Error code')
    details: dict[str, Any] | None = Field(None, description='Additional error details')


class ValidationError(BaseModel):
    field_errors: dict[str, list[str]] | None = Field(
        None, description='Field-specific validation errors'
    )
    non_field_errors: list[str] | None = Field(
        None, description='General validation errors'
    )


class PaginationMetadata(BaseModel):
    page: int = Field(..., description='Current page number', ge=1)
    limit: int = Field(..., description='Items per page', ge=1, le=100)
    total: int = Field(..., description='Total number of items', ge=0)
    has_next: bool = Field(..., description='Whether there is a next page')
    has_previous: bool = Field(..., description='Whether there is a previous page')


class PaginatedResponse(BaseModel):
    metadata: PaginationMetadata
    items: list[dict[str, Any]] = Field(..., description='List of items')


class LicenseState(Enum):
    ready = 'ready'
    active = 'active'
    returned = 'returned'
    expired = 'expired'
    revoked = 'revoked'
    cancelled = 'cancelled'


class AppsReadiumSerializersLicenseSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    entry_id: UUID = Field(..., title='Entry Id')
    user_id: UUID = Field(..., title='User Id')
    state: LicenseState
    starts_at: datetime = Field(..., title='Starts At')
    expires_at: datetime = Field(..., title='Expires At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersAnnotationAnnotationSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    user_acquisition_id: UUID = Field(..., title='User Acquisition Id')
    title: str = Field(..., title='Title')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AcquisitionMIME(Enum):
    application_pdf = 'application/pdf'
    application_epub_zip = 'application/epub+zip'
    application_x_mobipocket_ebook = 'application/x-mobipocket-ebook'
    application_webpub_zip = 'application/webpub+zip'


class AcquisitionType(Enum):
    acquisition = 'acquisition'
    open_access = 'open-access'
    borrow = 'borrow'


class AppsApiSerializersEntriesAcquisitionSerializerDetailed(BaseModel):
    relation: AcquisitionType
    mime: AcquisitionMIME
    url: str | None = Field(None, title='Url')
    id: UUID = Field(..., title='Id')
    base64: str = Field(..., title='Base64')
    checksum: str = Field(..., title='Checksum')


class AppsApiSerializersEntriesCategorySerializerDetailed(BaseModel):
    id: UUID = Field(..., title='Id')
    term: str = Field(..., title='Term')
    catalog_id: UUID = Field(..., title='Catalog Id')
    label: str = Field(..., title='Label')
    scheme: str = Field(..., title='Scheme')


class AppsApiSerializersEntriesAuthorSerializerDetailed(BaseModel):
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    surname: str = Field(..., title='Surname')
    catalog_id: UUID = Field(..., title='Catalog Id')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class DetailType(Enum):
    field_out_of_range = '/out-of-range'
    field_not_found = '/not-found'
    field_validation_error = '/validation-error'
    field_conflict = '/conflict'


class ValidationErrorItem(BaseModel):
    code: str | None = Field(None, title='Code')
    message: str = Field(..., title='Message')
    path: list[str] | None = Field(None, title='Path')


class AppsCoreErrorsValidationError(BaseModel):
    title: str = Field(..., title='Title')
    type: DetailType | None = None
    detail: str | None = Field(None, title='Detail')
    trace: list[str] | None = Field(None, title='Trace')
    additional_data: Any | None = Field(None, title='Additional Data')
    validation_errors: list[ValidationErrorItem] = Field(..., title='Validation Errors')


class Minimal(BaseModel):
    id: UUID = Field(..., title='Id')
    username: str = Field(..., title='Username')
    name: str = Field(..., title='Name')
    surname: str = Field(..., title='Surname')


class UserCatalog(BaseModel):
    mode: str = Field(..., title='Mode')
    user: Minimal


class AppsApiSerializersCatalogsCatalogSerializerDetailed(BaseModel):
    id: UUID = Field(..., title='Id')
    creator_id: UUID = Field(..., title='Creator Id')
    url_name: str = Field(..., title='Url Name')
    title: str = Field(..., title='Title')
    is_public: bool = Field(..., title='Is Public')
    touched_at: datetime = Field(..., title='Touched At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')
    user_catalogs: list[UserCatalog] | None = Field(
        default_factory=list, title='User Catalogs'
    )


class Mode(Enum):
    read = 'read'
    write = 'write'
    manage = 'manage'


class AppsCoreErrorsProblemDetail(BaseModel):
    title: str = Field(..., title='Title')
    type: DetailType | None = None
    detail: str | None = Field(None, title='Detail')
    trace: list[str] | None = Field(None, title='Trace')
    additional_data: Any | None = Field(None, title='Additional Data')


class FeedKind(Enum):
    navigation = 'navigation'
    acquisition = 'acquisition'


class Nested(BaseModel):
    relation: AcquisitionType
    mime: AcquisitionMIME
    url: str | None = Field(None, title='Url')


class UserAcquisitionType(Enum):
    shared = 'shared'
    personal = 'personal'
    lcp = 'lcp'


class StatusStatistics(BaseModel):
    catalogs: int = Field(..., title='Catalogs')
    entries: int = Field(..., title='Entries')
    acquisitions: int = Field(..., title='Acquisitions')
    users: int = Field(..., title='Users')


class AppsApiSerializersStatusStatusSerializer(BaseModel):
    timestamp: datetime = Field(..., title='Timestamp')
    instance: str = Field(..., title='Instance')
    stats: StatusStatistics
    build: str | None = Field(None, title='Build')
    version: str | None = Field(None, title='Version')
    python: str | None = Field(None, title='Python')
    supervisord: dict[str, str] | None = Field(None, title='Supervisord')


class AppsApiSerializersAnnotationAnnotationItemSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    annotation_id: UUID = Field(..., title='Annotation Id')
    page: int = Field(..., title='Page')
    content: str = Field(..., title='Content')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersUsersUserSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    username: str = Field(..., title='Username')
    name: str = Field(..., title='Name')
    surname: str = Field(..., title='Surname')
    is_superuser: bool = Field(..., title='Is Superuser')
    is_active: bool = Field(..., title='Is Active')
    last_login: datetime = Field(..., title='Last Login')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersUsersUserSerializerDetailed(BaseModel):
    id: UUID = Field(..., title='Id')
    username: str = Field(..., title='Username')
    name: str = Field(..., title='Name')
    surname: str = Field(..., title='Surname')
    is_superuser: bool = Field(..., title='Is Superuser')
    is_active: bool = Field(..., title='Is Active')
    last_login: datetime = Field(..., title='Last Login')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')
    permissions: list[str] = Field(..., title='Permissions')
    catalog_permissions: dict[str, Mode] | None = Field(
        None, title='Catalog Permissions'
    )


class PaginationModel(BaseModel):
    page: int = Field(..., title='Page')
    limit: int = Field(..., title='Limit')
    pages: int = Field(..., title='Pages')
    total: int = Field(..., title='Total')


class RootModelTypeVar(BaseModel):
    __root__: Any = Field(..., title='RootModel[TypeVar]')


class AppsApiResponsePaginationResponseModel(BaseModel):
    items: RootModelTypeVar
    metadata: PaginationModel


class AppsApiResponsePaginationModel(PaginationModel):
    pass


class AppsApiSerializersEntriesAcquisitionSerializerBase(BaseModel):
    relation: AcquisitionType
    mime: AcquisitionMIME
    url: str | None = Field(None, title='Url')
    id: UUID = Field(..., title='Id')


class AppsApiSerializersCatalogsUserCatalog(UserCatalog):
    pass


class AppsApiSerializersStatusStatusStatistics(StatusStatistics):
    pass


class AppsCoreErrorsValidationErrorItem(ValidationErrorItem):
    pass


class AppsApiSerializersCatalogsCatalogSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    creator_id: UUID = Field(..., title='Creator Id')
    url_name: str = Field(..., title='Url Name')
    title: str = Field(..., title='Title')
    is_public: bool = Field(..., title='Is Public')
    touched_at: datetime = Field(..., title='Touched At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersTokensTokenSerializerRefresh(BaseModel):
    access_token: str = Field(..., title='Access Token')


class AppsApiResponseSingleResponseModel(BaseModel):
    response: Any = Field(..., title='Response')


class AppsApiSerializersEntriesAuthorSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    surname: str = Field(..., title='Surname')


class AppsApiSerializersUsersUserSerializerMinimal(Minimal):
    pass


class AppsApiSerializersApiKeysApiKeySerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    user_id: UUID = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    is_active: bool = Field(..., title='Is Active')
    last_seen_at: datetime = Field(..., title='Last Seen At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersEntriesLanguageSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    name: str = Field(..., title='Name')
    alpha2: str = Field(..., title='Alpha2')
    alpha3: str = Field(..., title='Alpha3')


class AppsApiSerializersEntriesCategorySerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    term: str = Field(..., title='Term')


class AppsApiSerializersEntriesAcquisitionSerializerNested(Nested):
    pass


class AppsApiSerializersFeedsFeedSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    catalog_id: UUID = Field(..., title='Catalog Id')
    parents: list[UUID] | None = Field([], title='Parents')
    children: list[UUID] | None = Field([], title='Children')
    creator_id: UUID = Field(..., title='Creator Id')
    title: str = Field(..., title='Title')
    kind: FeedKind
    url_name: str = Field(..., title='Url Name')
    url: str | None = Field(None, title='Url')
    content: str = Field(..., title='Content')
    per_page: int | None = Field(None, title='Per Page')
    touched_at: datetime = Field(..., title='Touched At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersEntriesEntrySerializerDetailed(BaseModel):
    id: UUID = Field(..., title='Id')
    creator_id: UUID = Field(..., title='Creator Id')
    catalog_id: UUID = Field(..., title='Catalog Id')
    shelf_record_id: UUID | None = Field(None, title='Shelf Record Id')
    entry_authors: list[AppsApiSerializersEntriesAuthorSerializerBase] | None = Field(
        None, title='Entry Authors'
    )
    categories: list[AppsApiSerializersEntriesCategorySerializerBase] | None = Field(
        None, title='Categories'
    )
    language: AppsApiSerializersEntriesLanguageSerializerBase
    feeds: list[AppsApiSerializersFeedsFeedSerializerBase] | None = Field(
        None, title='Feeds'
    )
    acquisitions: list[AppsApiSerializersEntriesAcquisitionSerializerBase] | None = (
        Field(None, title='Acquisitions')
    )
    popularity: int = Field(..., title='Popularity')
    title: str = Field(..., title='Title')
    summary: str = Field(..., title='Summary')
    image_url: str | None = Field(None, title='Image Url')
    image_mime: str = Field(..., title='Image Mime')
    thumbnail_url: str | None = Field(None, title='Thumbnail Url')
    config: dict[str, Any] = Field(..., title='Config')
    citation: str = Field(..., title='Citation')
    touched_at: datetime = Field(..., title='Touched At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')
    published_at: str = Field(..., title='Published At')
    publisher: str = Field(..., title='Publisher')
    content: str = Field(..., title='Content')
    identifiers: dict[str, Any] = Field(..., title='Identifiers')


class AuthorForm(BaseModel):
    name: str = Field(..., description='', max_length=255, title='name')
    surname: str = Field(..., description='', max_length=255, title='surname')


class EvilflowersRenderType(Enum):
    document = 'document'
    page = 'page'


class EntryConfigForm(BaseModel):
    evilflowers_ocr_enabled: bool | None = Field(
        None, description='', title='evilflowers_ocr_enabled'
    )
    evilflowers_ocr_rewrite: bool | None = Field(
        None, description='', title='evilflowers_ocr_rewrite'
    )
    evilflowers_annotations_create: bool | None = Field(
        None, description='', title='evilflowers_annotations_create'
    )
    evilflowers_viewer_print: bool | None = Field(
        None, description='', title='evilflowers_viewer_print'
    )
    evilflowers_share_enabled: bool | None = Field(
        None, description='', title='evilflowers_share_enabled'
    )
    evilflowers_metadata_fetch: bool | None = Field(
        None, description='', title='evilflowers_metadata_fetch'
    )
    readium_enabled: bool | None = Field(None, description='', title='readium_enabled')
    evilflowers_render_type: EvilflowersRenderType | None = Field(
        None, description='', title='evilflowers_render_type'
    )


class UpdateLicenseForm(BaseModel):
    state: LicenseState = Field(..., description='', title='state')
    duration: str = Field(
        ...,
        description='Duration in ISO 8601 format. Example: "PT1H30M" for 1 hour and 30 minutes.\nThe format is defined as follows:\n- "P" indicates the period.\n- "Y" for years, "M" for months, "D" for days.\n- "T" indicates the start of the time section.\n- "H" for hours, "M" for minutes, "S" for seconds.\n- Valid examples include:\n  - "PT30M" (30 minutes)\n  - "P1Y2M10DT5H30M" (1 year, 2 months, 10 days, 5 hours, and 30 minutes)',
        example='P14D',
        regex='^P(?!P)(?:(\\d+Y)?(\\d+M)?(\\d+D)?(T(?:(\\d+H)?(\\d+M)?(\\d+S)?))?)?$',
        title='duration',
    )


class AnnotationItemForm(BaseModel):
    annotation_id: UUID = Field(..., description='', title='annotation_id')
    content: str = Field(..., description='', title='content')
    page: int = Field(..., description='', title='page')


class UserAcquisitionForm(BaseModel):
    acquisition_id: UUID = Field(..., description='', title='acquisition_id')
    type: UserAcquisitionType = Field(..., description='', title='type')
    range: str | None = Field(None, description='', title='range')
    expire_at: datetime | None = Field(None, description='', title='expire_at')


class AccessTokenForm(BaseModel):
    username: str = Field(..., description='', max_length=200, title='username')
    password: str = Field(..., description='', title='password')


class UserCatalogForm(BaseModel):
    user_id: UUID = Field(..., description='', title='user_id')
    mode: Mode = Field(..., description='', title='mode')


class CreateAnnotationForm(BaseModel):
    user_acquisition_id: UUID = Field(..., description='', title='user_acquisition_id')
    title: str = Field(..., description='', title='title')


class CreateUserForm(BaseModel):
    name: str = Field(..., description='', max_length=30, title='name')
    surname: str = Field(..., description='', max_length=150, title='surname')
    password: str = Field(..., description='', title='password')
    is_active: bool | None = Field(None, description='', title='is_active')
    username: str = Field(..., description='', max_length=200, title='username')


class CreateLicenseForm(BaseModel):
    entry_id: UUID = Field(..., description='', title='entry_id')
    state: LicenseState = Field(..., description='', title='state')
    duration: str = Field(
        ...,
        description='Duration in ISO 8601 format. Example: "PT1H30M" for 1 hour and 30 minutes.\nThe format is defined as follows:\n- "P" indicates the period.\n- "Y" for years, "M" for months, "D" for days.\n- "T" indicates the start of the time section.\n- "H" for hours, "M" for minutes, "S" for seconds.\n- Valid examples include:\n  - "PT30M" (30 minutes)\n  - "P1Y2M10DT5H30M" (1 year, 2 months, 10 days, 5 hours, and 30 minutes)',
        example='P14D',
        regex='^P(?!P)(?:(\\d+Y)?(\\d+M)?(\\d+D)?(T(?:(\\d+H)?(\\d+M)?(\\d+S)?))?)?$',
        title='duration',
    )
    starts_at: datetime | None = Field(None, description='', title='starts_at')


class PriceForm(BaseModel):
    currency_code: str = Field(..., description='', title='currency_code')
    value: int = Field(..., description='', title='value')


class UserForm(BaseModel):
    name: str = Field(..., description='', max_length=30, title='name')
    surname: str = Field(..., description='', max_length=150, title='surname')
    password: str | None = Field(None, description='', title='password')
    is_active: bool | None = Field(None, description='', title='is_active')


class CategoryForm(BaseModel):
    catalog_id: UUID | None = Field(None, description='', title='catalog_id')
    term: str = Field(..., description='', max_length=255, title='term')
    label: str | None = Field(None, description='', max_length=255, title='label')
    scheme: str | None = Field(None, description='', max_length=255, title='scheme')


class ApiKeyForm(BaseModel):
    user_id: UUID | None = Field(None, description='', title='user_id')
    name: str | None = Field(None, description='', max_length=100, title='name')
    is_active: bool | None = Field(None, description='', title='is_active')


class CreateAuthorForm(BaseModel):
    name: str = Field(..., description='', max_length=255, title='name')
    surname: str = Field(..., description='', max_length=255, title='surname')
    catalog_id: UUID = Field(..., description='', title='catalog_id')


class RefreshTokenForm(BaseModel):
    refresh: str = Field(..., description='', title='refresh')


class ShelfRecordForm(BaseModel):
    entry_id: UUID = Field(..., description='', title='entry_id')


class FeedForm(BaseModel):
    catalog_id: UUID = Field(..., description='', title='catalog_id')
    title: str = Field(..., description='', max_length=100, title='title')
    url_name: str = Field(..., description='', max_length=50, title='url_name')
    kind: FeedKind = Field(..., description='', title='kind')
    content: str = Field(..., description='', title='content')
    per_page: int | None = Field(None, description='', ge=1, title='per_page')
    entries: UUID | None = Field(None, description='', title='entries')
    parents: UUID | None = Field(None, description='', title='parents')


class UpdateAnnotationForm(BaseModel):
    title: str = Field(..., description='', title='title')


class Detailed(AppsApiSerializersUsersUserSerializerDetailed):
    pass


class AppsApiSerializersTokensTokenSerializerAccess(BaseModel):
    access_token: str = Field(..., title='Access Token')
    refresh_token: str = Field(..., title='Refresh Token')
    user: Detailed


class AppsApiSerializersEntriesEntrySerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    creator_id: UUID = Field(..., title='Creator Id')
    catalog_id: UUID = Field(..., title='Catalog Id')
    shelf_record_id: UUID | None = Field(None, title='Shelf Record Id')
    entry_authors: list[AppsApiSerializersEntriesAuthorSerializerBase] | None = Field(
        None, title='Entry Authors'
    )
    categories: list[AppsApiSerializersEntriesCategorySerializerBase] | None = Field(
        None, title='Categories'
    )
    language: AppsApiSerializersEntriesLanguageSerializerBase
    feeds: list[AppsApiSerializersFeedsFeedSerializerBase] | None = Field(
        None, title='Feeds'
    )
    acquisitions: list[AppsApiSerializersEntriesAcquisitionSerializerBase] | None = (
        Field(None, title='Acquisitions')
    )
    popularity: int = Field(..., title='Popularity')
    title: str = Field(..., title='Title')
    summary: str = Field(..., title='Summary')
    image_url: str | None = Field(None, title='Image Url')
    image_mime: str = Field(..., title='Image Mime')
    thumbnail_url: str | None = Field(None, title='Thumbnail Url')
    config: dict[str, Any] = Field(..., title='Config')
    citation: str = Field(..., title='Citation')
    touched_at: datetime = Field(..., title='Touched At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class CatalogForm(BaseModel):
    url_name: str = Field(..., description='', title='url_name')
    title: str = Field(..., description='', max_length=100, title='title')
    is_public: bool | None = Field(None, description='', title='is_public')
    users: list[UserCatalogForm] | None = Field(None, description='', title='users')


class AcquisitionForm(BaseModel):
    relation: AcquisitionType | None = Field(None, description='', title='relation')
    prices: list[PriceForm] | None = Field(None, description='', title='prices')
    content: AnyUrl = Field(..., description='', title='content')


class EntryForm(BaseModel):
    id: str | None = Field(None, description='', title='id')
    language_code: str = Field(..., description='', max_length=3, title='language_code')
    category_ids: UUID | None = Field(None, description='', title='category_ids')
    authors: list[AuthorForm] | None = Field(None, description='', title='authors')
    author_ids: UUID | None = Field(None, description='', title='author_ids')
    feeds: UUID | None = Field(None, description='', title='feeds')
    categories: list[CategoryForm] | None = Field(
        None, description='', title='categories'
    )
    title: str = Field(..., description='', max_length=255, title='title')
    publisher: str | None = Field(
        None, description='', max_length=255, title='publisher'
    )
    published_at: str | None = Field(None, description='', title='published_at')
    summary: str | None = Field(None, description='', title='summary')
    content: str | None = Field(None, description='', title='content')
    acquisitions: list[AcquisitionForm] | None = Field(
        None, description='', title='acquisitions'
    )
    identifiers: str | None = Field(None, description='', title='identifiers')
    image: AnyUrl | None = Field(None, description='', title='image')
    config: EntryConfigForm | None = Field(None, description='', title='config')
    citation: str | None = Field(None, description='', title='citation')


class AcquisitionMetaForm(BaseModel):
    relation: AcquisitionType | None = Field(None, description='', title='relation')
    prices: list[PriceForm] | None = Field(None, description='', title='prices')


class AppsApiSerializersUserAcquisitionsUserAcquisitionSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    type: UserAcquisitionType
    range: str = Field(..., title='Range')
    user: Minimal
    acquisition: Nested
    url: str | None = Field(None, title='Url')
    entry: AppsApiSerializersEntriesEntrySerializerBase
    expire_at: datetime = Field(..., title='Expire At')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')


class AppsApiSerializersShelfRecordsShelfRecordSerializerBase(BaseModel):
    id: UUID = Field(..., title='Id')
    user_id: UUID = Field(..., title='User Id')
    entry: AppsApiSerializersEntriesEntrySerializerBase
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime = Field(..., title='Updated At')
